#!/bin/bash

while [[ $# == 0 ]]
do
    echo ""
    echo "  Usage: trainer [command]"
    echo ""
    echo "      start       Boots the gunicorn server"
    echo "      test        Runs tests"
    echo ""
    break
done

# Parse argument
while [[ $# -ge 1 ]]
do
    arg="$1"
    arg2="$2"
    case $arg in
        start)
            gunicorn -b 0.0.0.0:80 --workers=4 src.app:app
            shift
            ;;
	    test)
            python -m pytest $arg2 --color=yes
            shift
            ;;
        *)
            echo "" 
            echo "  Argument '$arg' not recognized"
            ./trainer
            shift
            ;;
    esac
    break
done
